function(nyx_add_test name path)
    add_executable(${name} ${path})
    target_link_libraries(${name} PRIVATE nyxdb_core GTest::gtest_main)
    add_test(NAME ${name} COMMAND ${name})
endfunction()

nyx_add_test(result_test            common/result_test.cpp)
nyx_add_test(disk_manager_test      storage/disk/disk_manager_test.cpp)
nyx_add_test(column_page_test       storage/disk/column_page_test.cpp)
nyx_add_test(column_file_test       storage/disk/column_file_test.cpp)
nyx_add_test(table_test             storage/disk/table_test.cpp)
nyx_add_test(lru_k_replacer_test    storage/memory/lru_k_replacer_test.cpp)
nyx_add_test(buffer_pool_test       storage/memory/buffer_pool_test.cpp)
nyx_add_test(column_vector_test     executor/column_vector_test.cpp)
nyx_add_test(chunk_test             executor/chunk_test.cpp)
nyx_add_test(table_scan_test        executor/table_scan_test.cpp)
nyx_add_test(expression_test        executor/expression_test.cpp)
nyx_add_test(filter_test            executor/filter_test.cpp)
nyx_add_test(project_test           executor/project_test.cpp)
nyx_add_test(limit_test             executor/limit_test.cpp)
